### ISSUE TITLE
[Kubernetes / Docker swarm]: Migrate application to container cluster

### ISSUE THREAD

**Issue by AJNOURI** [CloudAssessments/learn-with-anthony-james#2]
Here is a couple of topics I would love to see in [Kubernetes / Docker swarm] courses. 
After deploying a Kuberenetes/Docker swarm infrastructure, the transition from physical/virtual application model to container-based model is crucial.

- How to make the transition seamlessly?
- How to migrate a classic application to microservices?
- Can we always deploy single process per container? If not, what is possibel issues? Should we deploy a process manager? What and how?
- What are the new container specificities to consider? Security?
- Classless and classful applications and persistency. What are the solutions out there?

What is your take on that people?

**Comment by pinehead** [comment]
Honestly, it sounds a lot like it would fit in the docker/container course rather than the kubernetes given the nature of both.

Are you looking for something like this

Containers in production
- Introduction to containers
- How containers solve scaling and business problems 
- How micro services work with containers
- Migrating and running monolith applications with containers
- Migrating monolithic applications to micro service oriented architecture. 
- Service structure concepts for containers

**Comment by AJNOURI** [comment]
Indeed, that outline looks great!
It is OK for me if it's part of docker/container.
